// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

var sum = 0
var term = 0
var index = 1
while (term < 4000000) {
  term = fibonacci(index)
  index += 1
  if (term % 2 == 0 && term < 4000000) sum += term
}

println(sum)

def fibonacci(number: Int): Int = {
  if (number == 1) {
    1
  } else if (number == 2) {
    2
  } else {
    fibonacci(number - 1) + fibonacci(number - 2)
  }
}